@startuml

hide footbox
autonumber

activate AppProperties
App -> AppProperties : get("plugins.file")
App <-- AppProperties : plugins file path
deactivate AppProperties
activate PluginsLoader
App -> PluginsLoader : loadFromFile(file)
deactivate PluginsLoader
activate ViewService
App -> ViewService : getView("MainLayout")
App <-- ViewService : view
deactivate ViewService
create Scene
App -> Scene : new(view)
activate Stage
App -> Stage : setScene(scene)
App -> Stage : show()
deactivate Stage
@enduml
